### ISSUE TITLE
Adding unique keys to strings in the result

### ISSUE THREAD

**Issue by PTaylour** [marcellosachs/react-string-replace-recursively#1]
Hi!

If `reactStringReplace` produces an mixed array that will include strings how do you avoid the `Each child in an array or iterator should have a unique "key" prop` warning on render?

Would you recommend wrapping all the raw strings array in spans so that they can have a key attached?

ie your main example becomes:
```
var parent = (
  <ParentComponent>
    {[<span key="1">I appreciate a good </span>,
     <Link key="2" to={"tags/#chairback"}>
       [<span key="3">#</span>,
        <span key="4" className='search-term-match'>chair</span>,
        <span key="5">back</span>]
     </Link>,
     <span key="6"> I must say</span>]}
  </ParentComponent>
);
```

**Comment by marcellosachs** [comment]
That's a good idea! Will get to this tomorrow...

**Comment by marcellosachs** [comment]
@PTaylour it seems it might be the case that raw strings do not need a 'key'.
Judging by this react fiddle - https://jsfiddle.net/69z2wepo/39978/
What do you think?
However, I do need to change things so that the elements which are components get keys.

**Comment by marcellosachs** [comment]
Just published new version `0.1.24` that allows you to add a unique key to components in the resulting array.
The function `matcherFn` specified in the `config` object will now receive a third parameter - `key`, which can be used to populate the `key` prop of a component : 
```
matcherFn: function (rawText, processed, key) {
   return <div key={key}>{processed}</div>
}
```

**Comment by PTaylour** [comment]
Great stuff!

**Comment by marcellosachs** [comment]
thanks!
